site_name: aspen
theme: readthedocs
repo_url: https://github.com/RD-Processa/Aspen

pages:
- Introducción: index.md
- Conceptos importantes: Overview.md
- Conectar con Aspen:
  - Registro de aplicaciones: App_Register.md
  - Asegurar una clave API: Securing_AppKey.md
  - Identificación de aplicaciones: App_Setup.md
  - Pasos para crear un JWT : JWT-Build.md
  - Solicitar un token de autenticación: JWT-Request.md
  - Generar un token de autenticación: Generate-Token.md
  - Enviar un token de autenticación: Send-Token.md
  - Cambiar el secreto de una aplicación: Update-AppSecret.md
- Tokenización de pagos: 
  - Generalidades: Tokenization.md
  - Generación de un token transaccional: Generate-PaymentToken.md
  - Validación de un token transaccional: Redeem-PaymentToken.md
  - Pago con token transaccional: Perform-Payment.md  
  - Solicitud de envío de token transaccional: Send-TrxToken.md  
  - Retiro con token transaccional: Perform-Withdrawal.md  
- Consulta de productos de un cliente: Inquiries-CustomerAccounts.md
- Administrar cuentas para transferencias de un cliente: Admin-CustomerTransferAccounts.md
- Validar códigos de activación (SMS): Management-ActivationCodes.md
- Anulación de una transacción: Perform-Refund.md  
- Reversos:
  - De pago con token transaccional: Perform-Payment-Reversal.md
  - De retiro con token transaccional: Perform-Withdrawal-Reversal.md
  - De anulación: Perform-Refund-Reversal.md
- (Apéndice) Mensajes de respuesta: Responses.md
